# Generated by Django 4.1.5 on 2023-01-31 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('District', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleNumer', models.TextField(max_length=6, null=True)),
                ('RouteName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='District.district')),
            ],
        ),
    ]
