# Generated by Django 4.1.5 on 2023-03-09 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Franchise/')),
                ('address', models.CharField(max_length=50)),
                ('mobile_no_1', models.CharField(max_length=10)),
                ('mobile_no_2', models.CharField(blank=True, max_length=10, null=True)),
                ('Date_of_joining', models.DateField(blank=True, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('district', models.ManyToManyField(blank=True, to='utility.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
