# Generated by Django 4.1.5 on 2023-02-14 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('District', '0002_alter_district_options_district_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('Count', models.PositiveIntegerField(blank=True, null=True)),
                ('adname', models.CharField(blank=True, max_length=50, null=True)),
                ('date_time', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Franchise/')),
                ('address', models.CharField(max_length=50)),
                ('mobile_no_1', models.CharField(max_length=10)),
                ('mobile_no_2', models.CharField(blank=True, max_length=10, null=True)),
                ('Date_of_joining', models.DateField(blank=True, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='District.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
