# Generated by Django 4.1.5 on 2023-02-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('bus_no', models.CharField(blank=True, max_length=15, null=True)),
                ('adname', models.CharField(blank=True, max_length=50, null=True)),
                ('date_time', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
