# Generated by Django 4.1.5 on 2023-02-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myads',
            name='bus_no',
        ),
        migrations.RemoveField(
            model_name='myads',
            name='city',
        ),
        migrations.AddField(
            model_name='myads',
            name='Count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
