# Generated by Django 4.1.5 on 2023-02-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_myads_bus_no_remove_myads_city_myads_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myads',
            name='imei',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
