# Generated by Django 4.1.5 on 2023-02-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('District', '0002_alter_district_options_district_is_active'),
        ('dashboard', '0002_myads_bus_no_myads_route_name_myads_route_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='district',
        ),
        migrations.AddField(
            model_name='franchise',
            name='district',
            field=models.ManyToManyField(blank=True, null=True, to='District.district'),
        ),
    ]
