# Generated by Django 4.1.5 on 2023-02-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_myads_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myads',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
