# Generated by Django 4.1.5 on 2023-03-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_franchise_district_franchise_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('result', models.TextField()),
            ],
        ),
    ]
