# Generated by Django 4.1.5 on 2023-02-12 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('District', '0002_alter_district_options_district_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_alter_myads_imei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pic/Franchise/')),
                ('address', models.CharField(max_length=50)),
                ('mobile_no_1', models.CharField(max_length=10)),
                ('mobile_no_2', models.CharField(blank=True, max_length=10, null=True)),
                ('Date_of_joining', models.DateField(blank=True, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='District.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
