# Generated by Django 4.1.5 on 2023-02-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='mobile_no_1',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='mobile_no_2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Franchise/'),
        ),
    ]
