# Generated by Django 4.1.5 on 2023-03-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_franchise_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskResult',
        ),
    ]
