# Generated by Django 4.1.5 on 2023-03-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_taskresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myads',
            options={'verbose_name_plural': 'MyAds'},
        ),
    ]
