# Generated by Django 4.1.5 on 2023-02-12 19:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_franchise_mobile_no_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='mobile_no_1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='mobile_no_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
