# Generated by Django 4.1.5 on 2023-01-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdName', models.CharField(max_length=30)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('TotalCount', models.IntegerField(blank=True, max_length=15, null=True)),
                ('No_of_Days', models.IntegerField(max_length=5)),
                ('EDC', models.IntegerField(max_length=5, null=True)),
                ('EMC', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
