# Generated by Django 4.1.5 on 2023-01-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='EDC',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='EMC',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='No_of_Days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ads',
            name='TotalCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
