# Generated by Django 4.1.5 on 2023-01-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ads_edc_alter_ads_emc_alter_ads_no_of_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name_plural': 'Ads'},
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='EDC',
            new_name='ECPD',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='EMC',
            new_name='ECPM',
        ),
        migrations.AddField(
            model_name='ads',
            name='AdNameTamil',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='BusCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='District',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
