# Generated by Django 4.1.5 on 2023-02-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_options_rename_edc_ads_ecpd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='EndDate',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='StartDate',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
