# Generated by Django 4.1.5 on 2023-02-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ads_enddate_alter_ads_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='EndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ads',
            name='StartDate',
            field=models.DateField(),
        ),
    ]
