# Generated by Django 4.1.5 on 2023-02-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('District', '0002_alter_district_options_district_is_active'),
        ('ads', '0005_alter_ads_enddate_alter_ads_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='District',
        ),
        migrations.AddField(
            model_name='ads',
            name='District',
            field=models.ManyToManyField(blank=True, null=True, to='District.district'),
        ),
    ]
