# Generated by Django 4.1.5 on 2023-03-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ads_display_alter_ads_adnametamil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='display',
            field=models.BooleanField(default=True, help_text='check this to display the ads'),
        ),
    ]
