# Generated by Django 4.1.5 on 2023-03-07 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('District', '0002_alter_district_options_district_is_active'),
        ('ads', '0010_rename_adnametamil_ads_adnameusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='agent',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ads',
            name='AdNameUsername',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='BusCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='District',
            field=models.ManyToManyField(to='District.district'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='TotalCount',
            field=models.IntegerField(null=True),
        ),
    ]
