# Generated by Django 4.1.5 on 2023-02-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('depo', models.CharField(max_length=20)),
                ('route_no', models.CharField(max_length=10)),
                ('route_name', models.CharField(max_length=50)),
                ('imei', models.CharField(max_length=20)),
                ('station', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
