# Generated by Django 4.1.5 on 2023-03-09 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('depo', models.CharField(max_length=20)),
                ('route_no', models.CharField(max_length=10)),
                ('route_name', models.CharField(max_length=50)),
                ('imei', models.CharField(max_length=20)),
                ('station', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(blank=True, max_length=20, null=True)),
                ('DistrictTamil', models.CharField(blank=True, max_length=50, null=True)),
                ('is_Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'District',
            },
        ),
        migrations.CreateModel(
            name='MyAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('Count', models.PositiveIntegerField(blank=True, null=True)),
                ('adname', models.CharField(blank=True, max_length=50, null=True)),
                ('bus_no', models.CharField(blank=True, max_length=50, null=True)),
                ('route_no', models.CharField(blank=True, max_length=50, null=True)),
                ('route_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_time', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'MyAds',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdName', models.CharField(max_length=30)),
                ('AdNameUsername', models.CharField(max_length=30, null=True, unique=True)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('TotalCount', models.IntegerField(null=True)),
                ('No_of_Days', models.IntegerField()),
                ('ECPD', models.IntegerField(null=True)),
                ('ECPM', models.IntegerField(null=True)),
                ('BusCount', models.IntegerField(null=True)),
                ('display', models.BooleanField(default=True, help_text='check this to display the ads')),
                ('District', models.ManyToManyField(to='utility.district')),
                ('agent', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ads',
            },
        ),
    ]
