# Generated by Django 4.1.5 on 2023-03-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_spots', models.PositiveIntegerField(null=True)),
                ('Filled', models.PositiveIntegerField(null=True)),
                ('Empty', models.PositiveIntegerField(null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.district')),
            ],
        ),
    ]
