# Generated by Django 4.1.5 on 2023-03-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_alter_slot_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='Invoice_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='Invoice_Status',
            field=models.CharField(blank=True, choices=[('Billed', 'Billed'), ('Not Billed', 'Not Billed'), ('Not Generated', 'Not Generated')], max_length=50, null=True),
        ),
    ]
