# Generated by Django 4.1.5 on 2023-03-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_ads_invoice_date_ads_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='Payment_Status',
            field=models.CharField(blank=True, choices=[('Credited', 'Credited'), ('Not Credited', 'Not Credited'), ('Not Generated', 'Not Generated')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='Invoice_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
