# Generated by Django 4.1.5 on 2023-02-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('District', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'District'},
        ),
        migrations.AddField(
            model_name='district',
            name='is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
